# Generated by Django 5.2.6 on 2025-09-18 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("link", models.URLField()),
                ("description", models.TextField()),
                ("source_name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=20)),
                ("source_icon", models.URLField()),
                ("date_published", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
