# Generated by Django 5.2.6 on 2025-09-18 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="image_url",
            field=models.URLField(default="None"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="video_url",
            field=models.URLField(default="None"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
