# Generated by Django 5.2.6 on 2025-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_api", "0002_newsarticle_image_url_newsarticle_video_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="date_published",
            field=models.DateTimeField(blank=True),
        ),
    ]
