# Generated by Django 5.2.7 on 2025-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_alter_newsarticle_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, default='https://example.com/no-video'),
        ),
    ]
