# Generated by Django 5.2.7 on 2025-10-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_alter_newsarticle_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
