# Generated by Django 5.2.7 on 2025-10-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_alter_newsarticle_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='date_published',
            new_name='pubDate',
        ),
    ]
