# Generated by Django 5.2.7 on 2025-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_rename_date_published_newsarticle_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, default='https://example.com/no-video', null=True),
        ),
    ]
