# Generated by Django 5.2.7 on 2025-10-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0007_alter_newsarticle_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
